### ISSUE TITLE
Target debuff bar Sleep Icon doesn't update

### ISSUE THREAD

**Issue by alexbunnykitty** [onimitch/HXUI#2]
debuff bar Sleep Icon doesn't update when a mob is woken by actions.
Dose update if wakes up over time.

**Comment by onimitch** [comment]
Unfortunately the debuff tracking in HXUI isn't 100% accurate.
There are a few limitations:

Debuff durations can vary based on the casters equipment/buffs etc, and while it's technically possible to do a decent guess from your own gear (some forks of HXUI have tried), it's basically impossible to calculate it if the debuff was cast from someone else, since we don't have access to their gear and how that might effect the durations.

The second problem is as you mention, if a debuff ends early, HXUI also doesn't see this. I think there are edge cases, like being cured by Sleep which could theoretically be captured, but it's going to get quite complicated fast to attempt to capture all these scenarios I think.

It's something that has been discussed before and I think generally the concensus is solving either of these problems is a decent chunk of work and even then, it still won't be 100% accurate.

I don't have any plans to attempt this work. Maintainance of the official HXUI repo is changing soon, so who knows maybe it might happen there, but I probably wouldn't bank on it.
